#!/usr/bin/env ruby

files   = %w[bash_profile bashrc gitconfig gitignore profile zshrc aliases]
this_dir = File.dirname(File.expand_path(__FILE__))

files.each do |f|
  target = "#{ENV['HOME']}/.#{f}"
  if File.exists? target
    puts "#{target} already exists"
  else
    puts "Creating #{target}"
    File.symlink("#{this_dir}/#{f}", target)
  end
end
